### ISSUE TITLE
requirements.txt'de eksik var

### ISSUE THREAD

**Issue by Samet195** [mustafaaydn/yazbel-net#1]
`text_generator.py` ve `data_loader.py` dosyalarında, `numpy` kütüphanesini içeaktarmışsınız, ama bunu `requirements.txt` dosyasına eklememişsiniz. 🙂

**Comment by mustafaaydn** [comment]
merhaba,

Şuradaki [yanıta ](https://stackoverflow.com/a/44455526/9332187) ve `tensorflow`un ilgili sürümünün [setup.py](https://github.com/tensorflow/tensorflow/blob/v2.3.2/tensorflow/tools/pip_package/setup.py#L63) dosyasına dayanarak `numpy`'ı ayriyeten `requirements.txt`ye yazmaya gerek yok zannedersem - `tensorflow`u yüklemeye çalışırken `numpy`ı da (ve birçok kütüphaneyi daha!) yüklüyor. Ama daha açık olmak adına yazılabilir haklısınız, bir zararı da olmaz heralde.

**Comment by Samet195** [comment]
>`tensorflow`'u yüklemeye çalışırken `numpy`'ı da (ve birçok kütüphaneyi daha!) yüklüyor.

Hmm... bunu bilmiyordum, kusura bakmayın. 😅
